# Generated by Django 4.2.7 on 2023-11-26 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='date_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='cryptoApp.CustomUser'),
        ),
    ]
