# Generated by Django 4.2.7 on 2023-11-16 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoApp', '0004_socialsprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('currency', models.CharField(max_length=3)),
                ('result', models.FloatField()),
                ('is_coin_to_currency', models.BooleanField()),
                ('coin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cryptoApp.coin')),
            ],
        ),
    ]
