# Generated by Django 4.2.7 on 2023-11-16 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoApp', '0005_currencyconverter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
