# Generated by Django 4.2.7 on 2023-11-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoApp', '0007_alter_coin_icon_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coin',
            name='icon_url',
            field=models.URLField(blank=True),
        ),
    ]
