# Generated by Django 4.2.7 on 2023-11-18 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoApp', '0006_currency'),
        ('cryptoApp', '0008_alter_coin_icon_url'),
    ]

    operations = [
    ]
