# Generated by Django 4.2.7 on 2023-11-18 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoApp', '0009_merge_0006_currency_0008_alter_coin_icon_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='coin',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
