# Generated by Django 4.2.7 on 2023-11-18 23:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoApp', '0010_coin_createddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='createdDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
