# Generated by Django 4.2.7 on 2023-11-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cryptoApp', '0005_article'),
        ('cryptoApp', '0011_customuser_createddate'),
    ]

    operations = [
    ]
